version: '3.8'
services:
#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
  server:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/script.gpt:/app/script.gpt
#    depends_on:
#      - frontend
