version: '3.8'
services:
  server:
    environment:
      - GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY=${GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/script.gpt:/app/script.gpt
