apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-poly-gpt.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["","apps"] # Core API group
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]