apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-poly-gpt.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64encode }}
  #OPENAI_BASE_URL: <BASE64_ENCODED_OPENAI_BASE_URL>
  #OPENAI_API_TYPE: <BASE64_ENCODED_OPENAI_API_TYPE>
  #OPENAI_AZURE_DEPLOYMENT: <BASE64_ENCODED_OPENAI_AZURE_DEPLOYMENT>
